print("##############################")
print("#                            #")
print("#    AMANDA ARVA SAFARAYA    #")
print("#       2410817220022        #")
print("#                            #")
print("##############################")