nama = input("Nama                    : ")
nim = input("NIM                     : ")
kelas = input("Kelas Paralel           : ")
ttl = input("Tempat/Tanggal Lahir    : ")
alamat = input("Alamat                  : ")
hobby = input("Hobby                   : ")
no_hp = input("No. HP                  : ")